# Generated by Django 5.1.1 on 2024-10-17 19:41

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventfile',
            name='file',
            field=models.FileField(upload_to=events.models.upload_file),
        ),
    ]
