# Generated by Django 4.2.16 on 2024-11-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventfile_description_eventfile_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventfile',
            name='title',
        ),
    ]
