# Generated by Django 4.2.15 on 2024-11-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("events", "0008_eventfile_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="organizations",
            field=models.ManyToManyField(
                related_name="events", to="organizations.organization"
            ),
        ),
        migrations.AlterField(
            model_name="eventparticipant",
            name="status",
            field=models.CharField(
                choices=[
                    ("Invited", "Invited"),
                    ("Confirmed", "Confirmed"),
                    ("Denied", "Denied"),
                    ("Maybe", "Maybe"),
                ],
                max_length=10,
            ),
        ),
    ]
