# Generated by Django 4.2.16 on 2024-11-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('confirmed', 'Confirmed')], max_length=10),
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
