# Generated by Django 4.2.16 on 2024-11-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organizationmember_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmember',
            name='approved',
        ),
    ]
