# Generated by Django 4.2.15 on 2024-10-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "myaccount",
            "0002_remove_user_authenticated_with_google_user_groups_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default="johndoe@gmail.com", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
