# Generated by Django 5.1.1 on 2024-10-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0007_alter_user_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
