# Generated by Django 5.1.1 on 2024-10-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
