# Generated by Django 5.1.1 on 2024-11-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0010_remove_user_date_of_birth_remove_user_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
