# Generated by Django 4.2.15 on 2024-11-07 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myaccount.models


class Migration(migrations.Migration):

    dependencies = [
        ("myaccount", "0011_user_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilePicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(upload_to=myaccount.models.profile_picture_path),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
